### ISSUE TITLE
DX: allow field creation on "vocabulary"

### ISSUE THREAD

**Issue by simongeorges** [makinacorpus/drupal-usync#1]
Currently, we are obliged to declare the field on taxonomies separately from the vocabulary itself, whereas on nodes & users, only one declaration is required. This is strange and not immediate to understand ;-)

Example code:

```
entity:
  vocabulary:
    my_vocabulary:
      name: "My name"

  taxonomy_term:
    my_vocabulary:
      field:
        my_field: true
```
