### ISSUE TITLE
When 'storage' key is used for a field, load its defaults

### ISSUE THREAD

**Issue by SebCorbin** [makinacorpus/drupal-usync#4]
Example:
```
field:
  myfield:
    label: Test
    type: test
    storage:
      type: virtual_field
```

This will work for creation, but upon update, exceptions will be raised, thus we need to load storage default with `$field['storage'] += field_info_storage_types($field['storage']['type']);`
